const vocabList = [
  { word: "anomaly", definition: "[이상] 변칙, 이례적인 것" }, // [web:41]
  { word: "equivocal", definition: "[두 갈래] 애매모호한, 다의적인" }, // [web:41]
  { word: "lucid", definition: "[빛나다] 명료한, 이해하기 쉬운" }, // [web:41]
  { word: "precipitate", definition: "[떨어뜨리다] 촉발하다, 성급한" }, // [web:41]
  { word: "assuage", definition: "[누그러뜨리다] 달래다, 완화하다" }, // [web:41]
  { word: "erudite", definition: "[배우다] 박식한, 학식 있는" }, // [web:41]
  { word: "opaque", definition: "[불투명] 불투명한, 난해한" }, // [web:41]
  { word: "prodigal", definition: "[흩뿌리다] 방탕한, 낭비하는" }, // [web:41]
  { word: "enigma", definition: "[수수께끼] 불가사의, 난해한 사람/것" }, // [web:41]
  { word: "fervid", definition: "[불타다] 열렬한, 열정적인" }, // [web:41]
  { word: "placate", definition: "[달래다] 달래다, 화를 가라앉히다" }, // [web:41]
  { word: "zeal", definition: "[열] 열의, 열성" }, // [web:41]
  { word: "abstain", definition: "[떼어두다] 삼가다, 절제하다" }, // [web:41]
  { word: "audacious", definition: "[대담] 대담한, 무모할 정도의; 불손한" }, // [web:41]
  { word: "desiccate", definition: "[마르다] 건조시키다, 바짝 말리다" }, // [web:41]
  { word: "gullible", definition: "[삼키다] 잘 속는, 쉽게 믿는" }, // [web:41]
  { word: "laudable", definition: "[칭찬] 칭찬할 만한, 가상한" }, // [web:41]
  { word: "pedant", definition: "[현학] 현학자, 규칙만 따지는 학자" }, // [web:41]
  { word: "vacillate", definition: "[흔들리다] 흔들리다, 우유부단하다" }, // [web:41]
  { word: "adulterate", definition: "[섞다] 품질을 떨어뜨리다, 불순물을 섞다" }, // [web:41]
  { word: "capricious", definition: "[변덕] 변덕스러운, 예측 불가의" }, // [web:41]
  { word: "engender", definition: "[낳다] 발생시키다, 야기하다" }, // [web:41]
  { word: "homogenous", definition: "[같다] 동질의, 균질한" }, // [web:41]
  { word: "loquacious", definition: "[말 많다] 수다스러운, 말이 많은" }, // [web:41]
  { word: "pragmatic", definition: "[실무] 실용적인, 실리적인" }, // [web:41]
  { word: "volatile", definition: "[날다] 변덕스러운, 휘발성의; 급변하는" }, // [web:41]
  { word: "apathy", definition: "[무감정] 무관심, 냉담" }, // [web:41]
  { word: "corroborate", definition: "[강화] 확증하다, 뒷받침하다" }, // [web:41]
  { word: "ephemeral", definition: "[하루살이] 덧없는, 단명한" }, // [web:41]
  { word: "laconic", definition: "[짧다] 간결한, 말수가 적은" }, // [web:41]
  { word: "mitigate", definition: "[부드럽게] 완화하다, 경감하다" }, // [web:41]
  { word: "propriety", definition: "[적절] 예의, 적절함" }, // [web:41]
  { word: "advocate", definition: "[옹호] 옹호하다, 지지하다; 옹호자" }, // [web:41]
  { word: "cacophony", definition: "[거친 소리] 불협화음, 소음" }, // [web:41]
  { word: "enervate", definition: "[힘 빼다] 기력을 약화시키다, 무기력하게 하다" }, // [web:41]
  { word: "ingenuous", definition: "[솔직] 순진한, 꾸밈없는" }, // [web:41]
  { word: "misanthrope", definition: "[인간 혐오] 염세가, 인간혐오자" }, // [web:41]
  { word: "paradox", definition: "[역설] 역설, 모순된 말" }, // [web:41]
  { word: "venerate", definition: "[경외] 공경하다, 깊이 존중하다" }, // [web:41]
  { word: "antipathy", definition: "[반감] 반감, 혐오" }, // [web:41]
  { word: "deride", definition: "[비웃다] 조롱하다, 깔보다" }, // [web:41]
  { word: "eulogy", definition: "[찬미] 추도 연설, 찬사" }, // [web:41]
  { word: "lethargic", definition: "[나른] 무기력한, 기력이 없는" }, // [web:41]
  { word: "obdurate", definition: "[굳다] 완고한, 고집 센" }, // [web:41]
  { word: "philanthropic", definition: "[인류 사랑] 박애의, 자선의" }, // [web:41]
  { word: "waver", definition: "[흔들리다] 망설이다, 동요하다" }, // [web:41]
  { word: "bolster", definition: "[베개 받치다] 강화하다, 지지하다" }, // [web:41]
  { word: "dissonance", definition: "[어긋남] 불협화, 불일치" }, // [web:41]
  { word: "garrulous", definition: "[수다] 수다스러운, 말 많은" }, // [web:41]
  { word: "malleable", definition: "[두드리다] 유연한, 잘 변하는" }, // [web:41]
  { word: "ostentation", definition: "[과시] 과시, 허세" }, // [web:41]
  { word: "prevaricate", definition: "[빗말하다] 얼버무리다, 둘러대다" } // [web:41]
];

//export default vocabList;
