const vocabList = [
  // 핵심 추상·철학
  { word: "axiom", definition: "[자명] 공리, 자명한 원리" }, // [attached_file:1]
  { word: "dogma", definition: "[교리] 독단적 신조, 정설" }, // [attached_file:1]
  { word: "ethos", definition: "[기풍] 공동체 특유의 가치관" }, // [attached_file:1]
  { word: "hegemony", definition: "[패권] 지배적 주도권" }, // [attached_file:1]
  { word: "paradigm", definition: "[전형] 이론적 틀, 모형" }, // [attached_file:1]
  { word: "teleology", definition: "[목적론] 목적에 의한 설명" }, // [attached_file:1]
  { word: "utilitarian", definition: "[공리주의] 실용적인, 효용 중심" }, // [attached_file:1]
  { word: "hedonism", definition: "[쾌락주의] 쾌락을 최고 선으로 보는 관점" }, // [attached_file:1]
  { word: "nihilism", definition: "[허무주의] 전통 가치의 부정" }, // [attached_file:1]
  { word: "ontology", definition: "[존재론] 존재의 본성 연구" }, // [attached_file:1]
  { word: "epistemology", definition: "[인식론] 지식의 근거 연구" }, // [attached_file:1]
  { word: "empiricism", definition: "[경험론] 경험 근거 지식" }, // [attached_file:1]
  { word: "reductionism", definition: "[환원주의] 단순 요소로 설명" }, // [attached_file:1]
  { word: "determinism", definition: "[결정론] 인과로 고정됨" }, // [attached_file:1]
  { word: "relativism", definition: "[상대주의] 절대 진리 부정" }, // [attached_file:1]
  { word: "absolutism", definition: "[절대주의] 절대 기준 옹호" }, // [attached_file:1]
  { word: "dialectic", definition: "[변증법] 논박 통한 진리 탐구" }, // [attached_file:1]
  { word: "orthodoxy", definition: "[정통] 인준된 신념" }, // [attached_file:1]
  { word: "heterodoxy", definition: "[이단] 비정통적 견해" }, // [attached_file:1]

  // 정책·행정·거버넌스
  { word: "bureaucratic", definition: "[관료적] 절차주의적" }, // [attached_file:1]
  { word: "technocrat", definition: "[기술관료] 전문지식 엘리트" }, // [attached_file:1]
  { word: "autocratic", definition: "[독재적] 전제의" }, // [attached_file:1]
  { word: "plutocracy", definition: "[금권정치] 부자 지배" }, // [attached_file:1]
  { word: "oligarchy", definition: "[과두정] 소수 지배" }, // [attached_file:1]
  { word: "populism", definition: "[포퓰리즘] 대중영합주의" }, // [attached_file:1]
  { word: "partisanship", definition: "[당파성] 편파성" }, // [attached_file:1]
  { word: "bipartisanship", definition: "[초당성] 양당 협력" }, // [attached_file:1]
  { word: "incumbency", definition: "[재직] 현직 신분" }, // [attached_file:1]
  { word: "constituency", definition: "[선거구민] 지지 기반" }, // [attached_file:1]
  { word: "referendum", definition: "[국민투표] 직접 표결" }, // [attached_file:1]
  { word: "plebiscite", definition: "[민중투표] 국민투표" }, // [attached_file:1]
  { word: "jurisprudence", definition: "[법학] 판례학" }, // [attached_file:1]
  { word: "codify", definition: "[성문화] 법전으로 만들다" }, // [attached_file:1]
  { word: "adjudicate", definition: "[재판] 판결하다" }, // [attached_file:1]
  { word: "injunction", definition: "[금지명령] 법원 명령" }, // [attached_file:1]
  { word: "restitution", definition: "[반환] 배상, 원상회복" }, // [attached_file:1]
  { word: "reparation", definition: "[배상] 손해 보상" }, // [attached_file:1]
  { word: "amnesty", definition: "[사면] 대사" }, // [attached_file:1]
  { word: "indemnity", definition: "[면책/보상] 배상금" }, // [attached_file:1]
  { word: "authoritarian", definition: "[권위주의] 강권적" }, // [attached_file:1]
  { word: "totalitarian", definition: "[전체주의] 전면 통제의" }, // [attached_file:1]

  // 교육·평가·학문
  { word: "pedagogy", definition: "[교육학] 교수법" }, // [attached_file:1]
  { word: "didactic", definition: "[교훈적] 가르치려 드는" }, // [attached_file:1]
  { word: "curricular", definition: "[교육과정의] 교과의" }, // [attached_file:1]
  { word: "extracurricular", definition: "[교과외] 비교과의" }, // [attached_file:1]
  { word: "interdisciplinary", definition: "[학제간] 융합 학문" }, // [attached_file:1]
  { word: "cross‑disciplinary", definition: "[교차분과] 학제 가로지름" }, // [attached_file:1]
  { word: "expository", definition: "[설명적] 해설의" }, // [attached_file:1]
  { word: "heuristic", definition: "[발견적] 탐구 유도" }, // [attached_file:1]
  { word: "formative", definition: "[형성평가] 형성적" }, // [attached_file:1]
  { word: "summative", definition: "[총괄평가] 총괄적" }, // [attached_file:1]
  { word: "remediation", definition: "[보충] 교정 학습" }, // [attached_file:1]
  { word: "metacognition", definition: "[메타인지] 사고에 대한 인지" }, // [attached_file:1]
  { word: "rubric", definition: "[채점기준] 평가표" }, // [attached_file:1]
  { word: "proctor", definition: "[감독관] 시험감독" }, // [attached_file:1]
  { word: "invigilate", definition: "[감독] 시험감독하다" }, // [attached_file:1]
  { word: "apprenticeship", definition: "[도제] 견습 제도" }, // [attached_file:1]
  { word: "tutelage", definition: "[보호/지도] 감독" }, // [attached_file:1]

  // 과학·연구 방법론
  { word: "hypothesis", definition: "[가설] 검증 전 설명" }, // [attached_file:1]
  { word: "falsifiable", definition: "[반증가능] 거짓 판별 가능" }, // [attached_file:1]
  { word: "reproducibility", definition: "[재현성] 반복 검증 가능" }, // [attached_file:1]
  { word: "confounding", definition: "[혼입] 교란 요인" }, // [attached_file:1]
  { word: "bias", definition: "[편향] 체계적 치우침" }, // [attached_file:1]
  { word: "causality", definition: "[인과성] 원인‑결과 관계" }, // [attached_file:1]
  { word: "correlation", definition: "[상관] 연관 정도" }, // [attached_file:1]
  { word: "stochastic", definition: "[확률적] 무작위성의" }, // [attached_file:1]
  { word: "deterministic", definition: "[결정적] 규칙적 인과" }, // [attached_file:1]
  { word: "longitudinal", definition: "[종단] 장기 추적" }, // [attached_file:1]
  { word: "cross‑sectional", definition: "[횡단] 단면 분석" }, // [attached_file:1]
  { word: "meta‑analysis", definition: "[메타분석] 연구 통합" }, // [attached_file:1]
  { word: "peer review", definition: "[동료심사] 전문가 검토" }, // [attached_file:1]
  { word: "preprint", definition: "[사전공개본] 정식 전 공개" }, // [attached_file:1]
  { word: "serendipity", definition: "[우연발견] 뜻밖의 발견" }, // [attached_file:1]
  { word: "fortuitous", definition: "[우발적] 우연한" }, // [attached_file:1]
  { word: "nascent", definition: "[초기] 막 생겨나는" }, // [attached_file:1]
  { word: "seminal", definition: "[기념비적] 시원적·영향 큼" }, // [attached_file:1]
  { word: "cutting‑edge", definition: "[최첨단] 선도적" }, // [attached_file:1]
  { word: "translational", definition: "[중개연구] 실용 전환" }, // [attached_file:1]
  { word: "consequentialist", definition: "[결과주의] 결과 중시" }, // [attached_file:1]
  { word: "precautionary", definition: "[예방적] 사전주의의" }, // [attached_file:1]

  // 사회·문화·윤리
  { word: "cosmopolitan", definition: "[세계시민적] 국제적" }, // [attached_file:1]
  { word: "parochial", definition: "[편협한] 지역적 한정" }, // [attached_file:1]
  { word: "paragon", definition: "[전형] 모범" }, // [attached_file:1]
  { word: "archetype", definition: "[원형] 전형적 모델" }, // [attached_file:1]
  { word: "zeitgeist", definition: "[시대정신] 시대 분위기" }, // [attached_file:1]
  { word: "mores", definition: "[관습윤리] 사회 규범" }, // [attached_file:1]
  { word: "propriety", definition: "[예의바름] 적절성" }, // [attached_file:1]
  { word: "decorum", definition: "[품위] 예의정돈" }, // [attached_file:1]
  { word: "iconoclast", definition: "[우상파괴자] 기존 타파자" }, // [attached_file:1]
  { word: "contrarian", definition: "[역행자] 반대투자자·반대자" }, // [attached_file:1]
  { word: "altruism", definition: "[이타주의] 타인 배려" }, // [attached_file:1]
  { word: "self‑interest", definition: "[자기이익] 사익 추구" }, // [attached_file:1]
  { word: "magnanimity", definition: "[도량] 관대함" }, // [attached_file:1]
  { word: "philanthropy", definition: "[박애] 자선 활동" }, // [attached_file:1]
  { word: "patronage", definition: "[후원] 메세나" }, // [attached_file:1]
  { word: "censorship", definition: "[검열] 정보 차단" }, // [attached_file:1]
  { word: "propaganda", definition: "[선전] 편향 홍보" }, // [attached_file:1]

  // 예술·미학
  { word: "aesthetic", definition: "[미학적] 심미의" }, // [attached_file:1]
  { word: "avant‑garde", definition: "[전위] 실험적 예술" }, // [attached_file:1]
  { word: "pastiche", definition: "[혼성모방] 패스티시" }, // [attached_file:1]
  { word: "kitsch", definition: "[키치] 저속한 미감" }, // [attached_file:1]
  { word: "accessible", definition: "[이해용이] 대중 친화" }, // [attached_file:1]
  { word: "hermetic", definition: "[난해] 밀봉·비전문적 폐쇄" }, // [attached_file:1]
  { word: "esoteric", definition: "[심원] 소수만 이해" }, // [attached_file:1]
  { word: "opaque", definition: "[불투명] 난해한" }, // [attached_file:1]
  { word: "legible", definition: "[가독] 잘 읽힘" }, // [attached_file:1]
  { word: "didacticism", definition: "[교훈주의] 교화적 성향" }, // [attached_file:1]
  { word: "patronage", definition: "[후원] 예술 후원" }, // [attached_file:1]
  { word: "curation", definition: "[큐레이션] 선별·전시 기획" }, // [attached_file:1]
  { word: "canon", definition: "[정전] 권위 있는 목록" }, // [attached_file:1]
  { word: "apocrypha", definition: "[외경/위서] 정전 밖 저작" }, // [attached_file:1]

  // 생태·환경·보전
  { word: "biodiversity", definition: "[생물다양성] 종 다양성" }, // [attached_file:1]
  { word: "keystone species", definition: "[핵심종] 생태계 핵심 종" }, // [attached_file:1]
  { word: "habitat", definition: "[서식지] 거주 환경" }, // [attached_file:1]
  { word: "preservation", definition: "[보존] 원형 유지" }, // [attached_file:1]
  { word: "conservation", definition: "[보전] 현명한 관리" }, // [attached_file:1]
  { word: "restoration", definition: "[복원] 원상 회복" }, // [attached_file:1]
  { word: "extinction", definition: "[멸종] 소멸" }, // [attached_file:1]
  { word: "endangered", definition: "[멸종위기] 위험에 처한" }, // [attached_file:1]
  { word: "endemic", definition: "[고유종] 특정 지역 한정" }, // [attached_file:1]
  { word: "invasive", definition: "[침입종] 생태 교란" }, // [attached_file:1]
  { word: "stewardship", definition: "[관리책임] 자원 관리" }, // [attached_file:1]
  { word: "sustainability", definition: "[지속가능성] 장기 유지" }, // [attached_file:1]
  { word: "externalities", definition: "[외부효과] 간접 비용/편익" }, // [attached_file:1]
  { word: "cost‑benefit", definition: "[비용‑편익] 효율 분석" }, // [attached_file:1]
  { word: "trade‑off", definition: "[절충] 상충 관계" }, // [attached_file:1]

  // 경제·노동·기술
  { word: "efficiency", definition: "[효율] 산출 대비 투입" }, // [attached_file:1]
  { word: "productivity", definition: "[생산성] 단위 산출" }, // [attached_file:1]
  { word: "optimization", definition: "[최적화] 최대 성과화" }, // [attached_file:1]
  { word: "automation", definition: "[자동화] 기계 대체" }, // [attached_file:1]
  { word: "displacement", definition: "[대체] 일자리 축출" }, // [attached_file:1]
  { word: "scalability", definition: "[확장성] 규모 확장 용이" }, // [attached_file:1]
  { word: "externality", definition: "[외부효과] 간접 영향" }, // [attached_file:1]
  { word: "incentive", definition: "[유인] 동기 부여" }, // [attached_file:1]
  { word: "subsidy", definition: "[보조금] 지원금" }, // [attached_file:1]
  { word: "austerity", definition: "[긴축] 지출 절감" }, // [attached_file:1]
  { word: "stimulus", definition: "[경기부양] 자극책" }, // [attached_file:1]
  { word: "opportunity cost", definition: "[기회비용] 포기 대가" }, // [attached_file:1]
  { word: "sunk cost", definition: "[매몰비용] 회수 불가 비용" }, // [attached_file:1]
  { word: "diminishing returns", definition: "[수확체감] 한계효용 감소" }, // [attached_file:1]

  // 수사·논증·비판적 사고
  { word: "premise", definition: "[전제] 논증 출발점" }, // [attached_file:1]
  { word: "inference", definition: "[추론] 결론 도출" }, // [attached_file:1]
  { word: "syllogism", definition: "[삼단논법] 연역 구조" }, // [attached_file:1]
  { word: "fallacy", definition: "[오류] 논리적 잘못" }, // [attached_file:1]
  { word: "non sequitur", definition: "[논리비약] 앞뒤 불일치" }, // [attached_file:1]
  { word: "ad hominem", definition: "[인신공격] 주장자 공격" }, // [attached_file:1]
  { word: "equivocation", definition: "[동어혼용] 애매한 말장난" }, // [attached_file:1]
  { word: "tautology", definition: "[동어반복] 순환 논증" }, // [attached_file:1]
  { word: "falsification", definition: "[반증] 거짓임 입증" }, // [attached_file:1]
  { word: "corroborate", definition: "[입증강화] 증거 보강" }, // [attached_file:1]
  { word: "refute", definition: "[논박] 틀렸음을 입증" }, // [attached_file:1]
  { word: "rebut", definition: "[반박] 반증 제시" }, // [attached_file:1]
  { word: "counterexample", definition: "[반례] 예외 사례" }, // [attached_file:1]
  { word: "caveat", definition: "[주의] 경고·단서" }, // [attached_file:1]
  { word: "caveat emptor", definition: "[구매자 유의] 하자 책임 경고" }, // [attached_file:1]
  { word: "axiomatic", definition: "[자명한] 자명하여 증명 불요" }, // [attached_file:1]

  // 빈출 고난도 형용사
  { word: "intractable", definition: "[난치] 다루기 어려운" }, // [attached_file:1]
  { word: "intransigent", definition: "[비타협] 완고한" }, // [attached_file:1]
  { word: "obdurate", definition: "[완고] 고집 센" }, // [attached_file:1]
  { word: "recalcitrant", definition: "[저항적] 반항적인" }, // [attached_file:1]
  { word: "capricious", definition: "[변덕] 예측 불가" }, // [attached_file:1]
  { word: "mercurial", definition: "[급변] 변덕 심한" }, // [attached_file:1]
  { word: "tenuous", definition: "[빈약] 미약한·희박한" }, // [attached_file:1]
  { word: "specious", definition: "[겉그럴듯] 허울좋은" }, // [attached_file:1]
  { word: "spurious", definition: "[가짜] 위조·허위의" }, // [attached_file:1]
  { word: "fallacious", definition: "[그릇된] 오류의" }, // [attached_file:1]
  { word: "unequivocal", definition: "[명백] 모호하지 않은" }, // [attached_file:1]
  { word: "equivocal", definition: "[애매] 다의적" }, // [attached_file:1]
  { word: "ambivalent", definition: "[양가감정] 상반 감정" }, // [attached_file:1]
  { word: "nebulous", definition: "[모호] 흐릿한" }, // [attached_file:1]
  { word: "recondite", definition: "[난해] 심원한" }, // [attached_file:1]
  { word: "arcane", definition: "[비의] 소수만 아는" }, // [attached_file:1]
  { word: "esoteric", definition: "[심오] 난해한" }, // [attached_file:1]
  { word: "abstruse", definition: "[난해] 이해 어려운" }, // [attached_file:1]
  { word: "ostensible", definition: "[표면상] 겉보기의" }, // [attached_file:1]
  { word: "putative", definition: "[추정상] 소문난" }, // [attached_file:1]

  // 태도·성향 표현
  { word: "complacent", definition: "[자기만족] 현실 안주" }, // [attached_file:1]
  { word: "diffident", definition: "[소심] 자신 없는" }, // [attached_file:1]
  { word: "reticent", definition: "[과묵] 말수가 적은" }, // [attached_file:1]
  { word: "vociferous", definition: "[시끄럽게 주장] 떠들썩한" }, // [attached_file:1]
  { word: "zealous", definition: "[열성] 열정적인" }, // [attached_file:1]
  { word: "fervent", definition: "[열렬] 강렬한" }, // [attached_file:1]
  { word: "indifferent", definition: "[무관심] 관심 없음" }, // [attached_file:1]
  { word: "apathetic", definition: "[무감각] 냉담한" }, // [attached_file:1]
  { word: "stoic", definition: "[금욕/무감] 스토아적인" }, // [attached_file:1]
  { word: "hedonistic", definition: "[쾌락주의적] 향락 추구" }, // [attached_file:1]
  { word: "ascetic", definition: "[금욕적] 절제된" }, // [attached_file:1]
  { word: "pragmatic", definition: "[실용적] 현실주의의" }, // [attached_file:1]
  { word: "idealistic", definition: "[이상주의적] 관념적인" }, // [attached_file:1]

  // 동사(격식/학술)
  { word: "substantiate", definition: "[입증] 근거로 뒷받침" }, // [attached_file:1]
  { word: "corroborate", definition: "[입증강화] 추가 증거로 뒷받침" }, // [attached_file:1]
  { word: "delineate", definition: "[윤곽 제시] 자세히 기술" }, // [attached_file:1]
  { word: "elucidate", definition: "[명료화] 분명히 밝히다" }, // [attached_file:1]
  { word: "enumerate", definition: "[열거] 하나하나 말하다" }, // [attached_file:1]
  { word: "extrapolate", definition: "[외삽] 추정 확대" }, // [attached_file:1]
  { word: "exacerbate", definition: "[악화] 더 심화시키다" }, // [attached_file:1]
  { word: "mitigate", definition: "[완화] 경감하다" }, // [attached_file:1]
  { word: "obviate", definition: "[제거] 불필요하게 만들다" }, // [attached_file:1]
  { word: "circumscribe", definition: "[제한] 경계짓다" }, // [attached_file:1]
  { word: "proscribe", definition: "[금지] 금하다" }, // [attached_file:1]
  { word: "prescribe", definition: "[규정/처방] 정하다" }, // [attached_file:1]
  { word: "disseminate", definition: "[전파] 널리 퍼뜨리다" }, // [attached_file:1]
  { word: "promulgate", definition: "[공표] 선포·반포하다" }, // [attached_file:1]
  { word: "repudiate", definition: "[부인/거부] 인정 않다" }, // [attached_file:1]
  { word: "rescind", definition: "[폐지] 철회·무효화" }, // [attached_file:1]
  { word: "abrogate", definition: "[폐기] (법·합의) 폐지" }, // [attached_file:1]

  // 라틴·그리스계 학술어
  { word: "status quo", definition: "[현상유지] 현재 상태" }, // [attached_file:1]
  { word: "prima facie", definition: "[일견] 겉보기에는" }, // [attached_file:1]
  { word: "a priori", definition: "[선험적] 경험 이전" }, // [attached_file:1]
  { word: "a posteriori", definition: "[후험적] 경험 이후" }, // [attached_file:1]
  { word: "sine qua non", definition: "[필수조건] 없어선 안 됨" }, // [attached_file:1]
  { word: "ad hoc", definition: "[특별] 임시 방편" }, // [attached_file:1]
  { word: "per se", definition: "[그 자체로] 본질적으로" }, // [attached_file:1]
  { word: "de facto", definition: "[사실상] 실질적으로" }, // [attached_file:1]
  { word: "de jure", definition: "[법률상] 법적으로" }, // [attached_file:1]
  { word: "ipso facto", definition: "[그 사실 자체로] 따라서" }, // [attached_file:1]
  { word: "quorum", definition: "[정족수] 의결 최소 인원" }, // [attached_file:1]
  { word: "modus operandi", definition: "[수법] 전형적 방식" }, // [attached_file:1]
];
export default vocabList;