const vocabList = [
  { word: "subvert", definition: "[전복하다] 뒤엎다, 파괴하다" }, // [web:41]
  { word: "respite", definition: "[휴식] 일시적인 휴식, 유예" }, // [web:41]
  { word: "deference", definition: "[존중] 존경, 경의" }, // [web:41]
  { word: "inescapable", definition: "[피할 수 없는] 불가피한, 필연적인" }, // [web:41]
  { word: "comprehensible", definition: "[이해할 수 있는] 이해하기 쉬운, 명료한" }, // [web:41]
  { word: "inexhaustible", definition: "[고갈되지 않는] 무진장한, 끊임없는" }, // [web:41]
  { word: "abrasive", definition: "[마모시키는] 거친, 신랄한" }, // [web:41]
  { word: "obscure", definition: "[가리다] 모호한, 불분명한" }, // [web:41]
  { word: "reiterate", definition: "[반복하다] 되풀이하다, 반복해서 말하다" }, // [web:41]
  { word: "antidote", definition: "[해독제] 해독제, 해결책" }, // [web:41]
  { word: "autobiography", definition: "[자서전] 자서전, 자기 이야기" }, // [web:41]
  { word: "persistence", definition: "[고집] 끈기, 지속성" }, // [web:41]
  { word: "quixotic", definition: "[공상적인] 비현실적인, 몽상적인" }, // [web:41]
  { word: "envision", definition: "[상상하다] 구상하다, 상상하다" }, // [web:41]
  { word: "inevitable", definition: "[불가피한] 피할 수 없는, 필연적인" }, // [web:41]
  { word: "diffused", definition: "[퍼지다] 확산된, 퍼진" }, // [web:41]
  { word: "unambiguous", definition: "[명확한] 분명한, 모호하지 않은" }, // [web:41]
  { word: "explicit", definition: "[명백한] 명시적인, 분명한" }, // [web:41]
  { word: "periphery", definition: "[주변] 주변부, 외곽" }, // [web:41]
  { word: "arbitrary", definition: "[임의의] 자의적인, 독단적인" }, // [web:41]
  { word: "abstracted", definition: "[추상적인] 추상화된, 멍한" }, // [web:41]
  { word: "proscribed", definition: "[금지된] 금지된, 배척된" }, // [web:41]
  { word: "prescribed", definition: "[규정된] 처방된, 규정된" }, // [web:41]
  { word: "discreet", definition: "[신중한] 조심스러운, 신중한" }, // [web:41]
  { word: "spurious", definition: "[거짓된] 가짜의, 위조된" }, // [web:41]
  { word: "fortuitous", definition: "[우연한] 우연한, 행운의" }, // [web:41]
  { word: "indolence", definition: "[게으름] 나태, 게으름" }, // [web:41]
  { word: "problematic", definition: "[문제의] 문제가 있는, 불확실한" }, // [web:41]
  { word: "fervent", definition: "[열렬한] 열정적인, 열렬한" }, // [web:41]
  { word: "compliance", definition: "[순응] 준수, 따름" }, // [web:41]
];